// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjTYbNK6gc7Nh8u6WNgAMjpmiMWrUEqg',
    appId: '1:812415835662:web:bfebbb96ddb51bc478e65f',
    messagingSenderId: '812415835662',
    projectId: 'notes-app-b3093',
    authDomain: 'notes-app-b3093.firebaseapp.com',
    storageBucket: 'notes-app-b3093.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2lyCSTF_KPnGYEQ5gxcNYLUJoql1c7I',
    appId: '1:812415835662:android:2f2b90a754759e3278e65f',
    messagingSenderId: '812415835662',
    projectId: 'notes-app-b3093',
    storageBucket: 'notes-app-b3093.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1rppxiczh2yesmV5UmLvZ0HZdFbESgg',
    appId: '1:812415835662:ios:2a4a93047650b37778e65f',
    messagingSenderId: '812415835662',
    projectId: 'notes-app-b3093',
    storageBucket: 'notes-app-b3093.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );
}
